print("Calculator The Driving Speed")
print("----------")
input("Where do you want to travel? : ")
length = float(input("The distance (km) = "))
time = float(input("Time of arrival (hr) = "))
print("----------")
print("Request speed =",length/time,"km/h")