print("Calculator Type")
print("----------")
a = float(input("Press Num.1 : "))
b = float(input("Press Num.2 : "))
print("----------")
print("Add :",a,"+",b,"=",a+b)
print("Subtract :",a,"+",b,"=",a-b)
print("Multiply :",a,"+",b,"=",a*b)
print("Divide :",a,"+",b,"=",a/b)
